package enums;

public enum ResponseCode {
    GAME_NOT_FOUND,
    MAX_PLAYERS_REACHED,
    NICK_ALREADY_EXISTS,
    INVALID_CHANCE,
    INVALID_MOVE,
    WORD_ALREADY_FOUND,
    INCORRECT_WORD,
    PLAYER_NOT_REGISTERED,
    UNAUTHORIZED_PLAYER,
    VALID_MOVE,
    GAME_IN_WAITING_STATE,
    GAME_COMPLETED;
}
